spring:
  application:
    name: employee-service
  config:
    import: "optional:configserver:http://localhost:9080"

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
          - health
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      employee-service:
        register-health-indicator: true
        event-consumer-buffer-size: 10
        failure-rate-threshold: 50
        minimum-number-of-calls: 10
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 5
        sliding-window-size: 10
        sliding-window-type: COUNT_BASED

  retry:
    instances:
      employee-service:
#        register-health-indicator: true
        max-attempts: 3
        wait-duration: 5s

  ratelimiter:
    instances:
      employee-service:
        register-health-indicator: false
        limit-for-period: 10
        limit-refresh-period: 10s
        timeout-duration: 3s
